// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4eweibull_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullsurvrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eweibullsurvsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammariz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammarizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammasimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammasurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammasurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammasurvrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ggammasurvsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllph_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllphriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllphsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gllphsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogistic_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticsurvrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4llogisticsurvsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalsurvrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lnormalsurvsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibull_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullph_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullphriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullphsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullphsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullsurv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullsurvriz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullsurvrizsimple_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibullsurvsimple_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4eweibull_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibull_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullsurvrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullsurvrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4eweibullsurvsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eweibullsurvsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammariz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammariz_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammarizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammarizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammasimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammasimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammasurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammasurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammasurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammasurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammasurvrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammasurvrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4ggammasurvsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ggammasurvsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllph_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllph_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllphriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllphriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllphsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllphsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4gllphsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gllphsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogistic_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogistic_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticsurvrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticsurvrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4llogisticsurvsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4llogisticsurvsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormal_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalsurvrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalsurvrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4lnormalsurvsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lnormalsurvsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibull_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullph_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullph_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullphriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullphriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullphsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullphsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullphsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullphsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullsurv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullsurv_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullsurvriz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullsurvriz_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullsurvrizsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullsurvrizsimple_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibullsurvsimple_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibullsurvsimple_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_JMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
