# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("eweibull", "eweibullriz", "eweibullrizsimple", "eweibullsimple", "eweibullsurv", "eweibullsurvriz", "eweibullsurvrizsimple", "eweibullsurvsimple", "ggamma", "ggammariz", "ggammarizsimple", "ggammasimple", "ggammasurv", "ggammasurvriz", "ggammasurvrizsimple", "ggammasurvsimple", "gllph", "gllphriz", "gllphsurv", "gllphsurvriz", "llogistic", "llogisticriz", "llogisticrizsimple", "llogisticsimple", "llogisticsurv", "llogisticsurvriz", "llogisticsurvrizsimple", "llogisticsurvsimple", "lnormal", "lnormalriz", "lnormalrizsimple", "lnormalsimple", "lnormalsurv", "lnormalsurvriz", "lnormalsurvrizsimple", "lnormalsurvsimple", "weibull", "weibullph", "weibullphriz", "weibullphsurv", "weibullphsurvriz", "weibullriz", "weibullrizsimple", "weibullsimple", "weibullsurv", "weibullsurvriz", "weibullsurvrizsimple", "weibullsurvsimple")

# load each stan module
Rcpp::loadModule("stan_fit4eweibull_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullsurvrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4eweibullsurvsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammariz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammarizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammasimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammasurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammasurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammasurvrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ggammasurvsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllph_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllphriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllphsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gllphsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogistic_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticsurvrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4llogisticsurvsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalsurvrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lnormalsurvsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibull_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullph_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullphriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullphsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullphsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullsurv_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullsurvriz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullsurvrizsimple_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibullsurvsimple_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
